backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "runners"
    label: "Runner"
    folder: "src/pages/runners"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "runner"}
      - {label: "Title (used for URL)", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Hedeflenen Bagis", name: "goaldonation", widget: "string"}
      - {label: "Toplanan Bagis", name: "totaldonation", widget: "string"}
      - {label: "Fonzip URL", name: "fonzip", widget: "string"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/iletisim/index.md"
        label: "İletişim"
        name: "iletisim"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}